let models=[]; const selected=new Set();
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>new Date(`${d}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const fmtShort=d=>new Date(`${d}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const fmtContext=n=>!n?'—':n>=1000000?`${(n/1000000).toFixed(n%1000000?1:0)}M`:`${Math.round(n/1000)}K`;
async function data(){try{const r=await fetch('data/models.json',{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){if(window.MODEL_DATA)return window.MODEL_DATA;throw e}}
function initMeta(d){const sorted=[...models].sort((a,b)=>b.released.localeCompare(a.released)),newest=sorted[0];$('#modelCount').textContent=models.length;$('#millionCount').textContent=models.filter(m=>(m.context||0)>=1e6||(m.extended_context||0)>=1e6).length;$('#openCount').textContent=models.filter(m=>/open/i.test(m.access)).length;$('#newestDate').textContent=fmtShort(newest.released);$('#newestModel').textContent=newest.model;$('#sourceCount').textContent=d.meta.sources_checked;$('#updated').textContent=`Reviewed ${fmtDate(d.meta.updated)} · ${d.meta.sources_checked} primary sources`;$('#footerUpdated').textContent=`Dataset reviewed ${fmtDate(d.meta.updated)}`;$('#briefingTitle').textContent=`${newest.model} is the newest tracked release`;$('#briefingText').textContent=`${newest.company} leads the release tape. ${models.filter(m=>(m.context||0)>=1e6).length} tracked models now state a native million-token context window.`}
function leaders(){const metrics=['reasoning','coding','agents','multimodal','efficiency'];const winnerByMetric=metrics.map(metric=>({metric,model:[...models].sort((a,b)=>b.scores[metric]-a.scores[metric])[0]}));$('#leaders').innerHTML=winnerByMetric.map((x,i)=>`<div class="leader-row" data-id="${x.model.id}"><span class="rank">0${i+1}</span><div class="leader-name"><strong>${esc(x.metric[0].toUpperCase()+x.metric.slice(1))}</strong><small>${esc(x.model.model)} · ${esc(x.model.company)}</small></div><span class="leader-score">${x.model.scores[x.metric]}</span><div class="spark"><i style="width:${x.model.scores[x.metric]}%"></i></div></div>`).join('');document.querySelectorAll('.leader-row').forEach(r=>r.addEventListener('click',()=>toggle(r.dataset.id,true)))}
function matrix(){const body=$('#matrix tbody');body.innerHTML=[...models].sort((a,b)=>Math.max(...Object.values(b.scores))-Math.max(...Object.values(a.scores))).map(m=>`<tr><td>${esc(m.model)}</td>${['reasoning','coding','agents','multimodal','efficiency'].map(k=>`<td><span class="heat" style="--v:${m.scores[k]}">${m.scores[k]}</span></td>`).join('')}<td>${fmtContext(m.context||m.extended_context)}</td><td>${/open/i.test(m.access)?'Open':'Hosted'}</td></tr>`).join('')}
function releases(){const sorted=[...models].sort((a,b)=>b.released.localeCompare(a.released));$('#releaseTape').innerHTML=sorted.slice(0,6).map(m=>`<div class="release-item"><time>${fmtShort(m.released)}</time><div><strong>${esc(m.model)}</strong><p>${esc(m.strengths.slice(0,3).join(' · '))}</p></div></div>`).join('')}
function contexts(){const top=[...models].filter(m=>m.context||m.extended_context).sort((a,b)=>(b.context||b.extended_context)-(a.context||a.extended_context)).slice(0,8),max=Math.max(...top.map(m=>m.context||m.extended_context));$('#contextBars').innerHTML=top.map(m=>`<div class="context-row"><span>${esc(m.model)}</span><div class="bar"><i style="width:${((m.context||m.extended_context)/max)*100}%"></i></div><strong>${fmtContext(m.context||m.extended_context)}</strong></div>`).join('')}
function access(){const open=models.filter(m=>/open/i.test(m.access)).length,hosted=models.filter(m=>!/open/i.test(m.access)).length,both=models.filter(m=>/open/i.test(m.access)&&/api|hosted/i.test(m.access)).length;const op=(open/models.length)*100,host=((open+hosted-both)/models.length)*100;$('#accessMix').innerHTML=`<div class="donut" style="--open:${op}%;--hosted:${host}%"></div><div class="legend"><div><i style="background:var(--accent)"></i>Open-linked ${open}</div><div><i style="background:var(--green)"></i>Hosted/API ${hosted}</div><div><i style="background:var(--rule)"></i>Overlap ${both}</div></div>`;const modalities=['Text','Code','Image','Video'];$('#modalityList').innerHTML=modalities.map(x=>{const n=models.filter(m=>m.modalities.includes(x)).length;return `<div><span><b>${x}</b><b>${n}/${models.length}</b></span><div class="mini-track"><i style="width:${n/models.length*100}%"></i></div></div>`}).join('')}
function ledger(){const groups=[...new Set(models.map(m=>m.company))].map(company=>({company,models:models.filter(m=>m.company===company)}));$('#sourceLedger').innerHTML=groups.map(g=>`<div class="source-row"><a href="${esc(g.models[0].source)}" target="_blank" rel="noopener">${esc(g.company)} ↗</a><span>${g.models.length} record${g.models.length>1?'s':''}<br>primary source</span></div>`).join('')}
function modelList(){const q=$('#search').value.toLowerCase(),filtered=models.filter(m=>JSON.stringify(m).toLowerCase().includes(q));$('#modelList').innerHTML=filtered.map(m=>`<article class="model-row"><input type="checkbox" aria-label="Compare ${esc(m.model)}" data-id="${m.id}" ${selected.has(m.id)?'checked':''}><div><h3>${esc(m.model)}</h3><p>${esc(m.company)} · ${fmtDate(m.released)}</p></div><div><small>CONTEXT</small><p>${fmtContext(m.context||m.extended_context)}</p></div><div class="tags">${m.strengths.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><a href="${esc(m.source)}" target="_blank" rel="noopener" aria-label="Open source for ${esc(m.model)}">↗</a></article>`).join('');document.querySelectorAll('.model-row input').forEach(i=>i.addEventListener('change',()=>toggle(i.dataset.id,false)))}
function toggle(id,scroll){if(selected.has(id))selected.delete(id);else if(selected.size<4)selected.add(id);renderTray();modelList();if(scroll)$('#explorer').scrollIntoView({behavior:'smooth',block:'start'})}
function renderTray(){const items=models.filter(m=>selected.has(m.id));$('#compareCount').textContent=`${items.length} / 4`;$('#compareTray').innerHTML=items.length?items.map(m=>`<article class="compare-card"><h3>${esc(m.model)}</h3><small>${esc(m.company)} · ${fmtContext(m.context||m.extended_context)} context</small><div class="score-grid">${[['R','reasoning'],['C','coding'],['A','agents'],['M','multimodal'],['E','efficiency']].map(([l,k])=>`<div><strong>${m.scores[k]}</strong><span>${l}</span></div>`).join('')}</div></article>`).join(''):'<p>Select up to four models. The broader field remains visible while this tray updates.</p>'}
function start(d){models=d.models||[];initMeta(d);leaders();matrix();releases();contexts();access();ledger();modelList();renderTray();$('#search').addEventListener('input',modelList);$('#clearCompare').addEventListener('click',()=>{selected.clear();modelList();renderTray()})}
data().then(start).catch(e=>{$('#briefingTitle').textContent='Dataset unavailable';$('#briefingText').textContent='Confirm data/models.js is present beside this page.';console.error(e)})
